spring.application.name=PracticaJAVA_Spring_JWT

#--- Conexion a PostgreSQL--
spring.datasource.url=jdbc:postgresql://localhost:5432/appweb2026ppa
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

#--- JPA / Hibernate--
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#--- Swagger / OpenAPI--
springdoc.swagger-ui.path=/swagger-ui.html

#--- Seguridad: JWT--
app.jwt.secret=cambia-esta-clave-larga-y-aleatoria-de-32-bytes-minimo
app.jwt.expiration-ms=3600000